// This file is auto-generated by @hey-api/openapi-ts

export type AddReservationCommand = {
    firstname: string;
    lastname: string;
    attendeeCount?: number | null;
    email: string;
    phoneNumber: string;
    sessionId?: string;
};

export type AuthenticatedResponseDto = {
    email?: string;
    fullName?: string;
    token?: string;
    tenant?: Tenant;
    roles?: Array<string>;
    tokenExpiry?: string;
};

export type CreateSessionCommand = {
    type: SessionType;
    title: string;
    description: string;
    start: string;
    end: string;
    location?: string;
    capacity?: number;
    tenantId: string;
};

export type EditSessionCommand = {
    id?: string;
    title: string;
    description: string;
    location?: string | null;
    capacity?: number;
};

export type EditTimeslotCommand = {
    sessionId?: string;
    start?: string;
    end?: string;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type PagedResponseDtoOfSessionBasic = {
    total?: number;
    items?: Array<SessionBasic>;
};

export type ReservationResponseDto = {
    reference: string;
    firstname: string;
    lastname: string;
    attendeeCount: number;
    email: string;
    phone: string;
};

export type SessionBasic = {
    id: string;
    title: string;
    description: string;
    location: string;
    start: string;
    end: string;
    type: SessionType;
    capacity: number;
    attendeeCount: number;
};

export type SessionResponseDto = {
    id?: string;
    title: string;
    description: string;
    location?: string;
    capacity?: number;
    start: string;
    end: string;
    type: SessionType2;
    reservations?: Array<ReservationResponseDto>;
};

export type SessionType = 'Individual' | 'Group';

export type SessionType2 = number;

export type Tenant = {
    id: string;
    description?: string;
    displayName?: string;
    name?: string;
};

export type GetApiReservationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reservations/{id}';
};

export type GetApiReservationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSessionsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        until?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/sessions';
};

export type GetApiSessionsResponses = {
    /**
     * OK
     */
    200: PagedResponseDtoOfSessionBasic;
};

export type GetApiSessionsResponse = GetApiSessionsResponses[keyof GetApiSessionsResponses];

export type PostApiSessionsData = {
    body: CreateSessionCommand;
    path?: never;
    query?: never;
    url: '/api/sessions';
};

export type PostApiSessionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type GetApiSessionsByIdResponses = {
    /**
     * OK
     */
    200: SessionResponseDto;
};

export type GetApiSessionsByIdResponse = GetApiSessionsByIdResponses[keyof GetApiSessionsByIdResponses];

export type PatchApiSessionsByIdData = {
    body: EditSessionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type PatchApiSessionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiSessionsByIdTimeslotData = {
    body: EditTimeslotCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}/timeslot';
};

export type PatchApiSessionsByIdTimeslotResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiSessionsBySessionIdReserveData = {
    body: AddReservationCommand;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/sessions/{sessionId}/reserve';
};

export type PostApiSessionsBySessionIdReserveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/current';
};

export type GetApiUsersCurrentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AuthenticatedResponseDto;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AuthenticatedResponseDto;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:7047/' | (string & {});
};