export const Errors = {
  NotEmptyError: 'NotEmptyError',
  DurationExceededError: 'DurationExceededError',
  GreaterThanDateError: 'GreaterThanDateError',
  GreaterThanError: 'GreaterThanError',
  InvalidPhoneNumberError: 'InvalidPhoneNumberError',
  LengthExceededError: 'LengthExceededError',
  LessThanDateError: 'LessThanDateError',
  NotDefaultError: 'NotDefaultError',
  NotFoundError: 'NotFoundError',
  InvalidEmailAddressError: 'InvalidEmailAddressError',
  NotEmptyValidator: 'NotEmptyValidator',
  MaximumLengthValidator: 'MaximumLengthValidator',
  LessThanOrEqualValidator: 'LessThanOrEqualValidator',
  GreaterThanOrEqualValidator: 'GreaterThanOrEqualValidator',
  GreaterThanValidator: 'GreaterThanValidator',
  LessThanValidator: 'LessThanValidator',
} as const;
